[package]
name = "web_server_with_database"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.8"
rusqlite = "0.26.0"
actix-files = "0.6.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0", features = ["derive"] }